# best result is obtained using DATAGRAD=0.003
NAME=cifar100_datagrad
mkdir -p couts/
echo $NAME

D=0
DATASET=cifar100
ITERS=50000
BS=128
LR=0.01
LRD=piecewise
WD=0.003
NET=cifarResnet
BN=True
TRAIN=20000
AUGMENTATION=False
WIDENESS=3

for C in `seq 1 1 1`
do
    echo ITER $C
    COMMON_ARGS="--MEMORY_SHARE=0.95 --DATASET=$DATASET --ITERS=$ITERS --BATCH_SIZE=$BS --LEARNING_RATE=$LR --LEARNING_RATE_DECAY=$LRD --WEIGHT_DECAY=$WD --DISC_TYPE=$NET --WIDENESS=$WIDENESS --DO_BATCHNORM=$BN --TRAIN_DATASET_SIZE=$TRAIN --AUGMENTATION=$AUGMENTATION"
    
    for DG in 0.0001 0.0003 0.001 0.003 0.01 0.03 0.1 0.3 1 3 10 30 100 0
    do
	echo DG $DG
	CUDA_VISIBLE_DEVICES=$D python classifier.py $COMMON_ARGS --RANDOM_SEED=$C --DATAGRAD=$DG > couts/$NAME.DG_${DG}_${C}.cout 2> couts/$NAME.DG_${DG}_${C}.cerr
    done
done

echo "DONE"
