NAME=cifar100_spect_wd
mkdir -p couts/
echo $NAME

D=1
DATASET=cifar100
ITERS=50000
BS=128
LR=0.01
LRD=piecewise
NET=cifarResnet
BN=True
TRAIN=20000
AUGMENTATION=False
WIDENESS=3
WD=0.003
LAMBDA_WITH_WD=0.003
LAMBDA=0.001

for C in `seq 1 1 10`
do
    echo ITER $C
	COMMON_ARGS="--RANDOM_SEED=$C --MEMORY_SHARE=0.95 --DATASET=$DATASET --ITERS=$ITERS --BATCH_SIZE=$BS --LEARNING_RATE=$LR --LEARNING_RATE_DECAY=$LRD --DISC_TYPE=$NET --WIDENESS=$WIDENESS --DO_BATCHNORM=$BN --TRAIN_DATASET_SIZE=$TRAIN --AUGMENTATION=$AUGMENTATION"

	echo BASELINE
	CUDA_VISIBLE_DEVICES=$D python classifier.py $COMMON_ARGS --WEIGHT_DECAY=0 > couts/$NAME.BASELINE_${C}.cout 2> couts/$NAME.BASELINE_${C}.cerr

#	echo WD
#	CUDA_VISIBLE_DEVICES=$D python classifier.py $COMMON_ARGS --WEIGHT_DECAY=$WD > couts/$NAME.WD_${C}.cout 2> couts/$NAME.WD_${C}.cerr

	echo SPECTREG
	CUDA_VISIBLE_DEVICES=$D python classifier.py $COMMON_ARGS --WEIGHT_DECAY=0 --LAMBDA=$LAMBDA > couts/$NAME.SPECT_${C}.cout 2> couts/$NAME.SPECT_${C}.cerr

#	echo SPECTREG+WD
#	CUDA_VISIBLE_DEVICES=$D python classifier.py $COMMON_ARGS --WEIGHT_DECAY=$WD --LAMBDA=$LAMBDA_WITH_WD > couts/$NAME.SPECT_WD_${C}.cout 2> couts/$NAME.SPECT_WD_${C}.cerr

done

echo "DONE"
