# CIFAR-10 3-wide N=3 resnet experiments with different DATAGRAD values

NAME=cifar10_3w_1
mkdir -p couts/

D=0
WD=0.003
TRAIN=50000
LRD=piecewise
NET=cifarResnet
WIDENESS=3
LEARNING_RATE=0.1
ITERS=50000
BS=128

for C in `seq 1 1 10`
do
    echo ITER $C
	COMMON_ARGS="--RANDOM_SEED=$C --MEMORY_SHARE=1 --DATASET=cifar10 --ITERS=$ITERS --BATCH_SIZE=$BS --LEARNING_RATE=$LEARNING_RATE --LEARNING_RATE_DECAY=$LRD --WEIGHT_DECAY=$WD --DISC_TYPE=$NET --WIDENESS=$WIDENESS --DO_BATCHNORM=True --TRAIN_DATASET_SIZE=$TRAIN"

	for DATAGRAD in 0 0.0001 0.0003 0.001 0.003 0.01 0.03 0.1 0.3 1
	do
		# NO AUG
		CUDA_VISIBLE_DEVICES=$D python classifier.py $COMMON_ARGS --DATAGRAD=$DATAGRAD > couts/$NAME.W_${WIDENESS}_DG_${DATAGRAD}_${C}.cout 2> couts/$NAME.W_${WIDENESS}_DG_${DATAGRAD}_${C}.cerr

		# AUG
		CUDA_VISIBLE_DEVICES=$D python classifier.py $COMMON_ARGS --DATAGRAD=$DATAGRAD --AUGMENTATION=1 > couts/$NAME.W_${WIDENESS}_DG_${DATAGRAD}_AUG_1_${C}.cout 2> couts/$NAME.W_${WIDENESS}_DG_${DATAGRAD}_AUG_1_${C}.cerr

	done
done
